workspace:
  base: /mnt
  path: /

pipeline:
  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=dev
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_staging_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=staging
    secrets:
      - source: STAGING_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_production_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=production
    secrets:
      - source: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  validate_schema:
    image: python:3.6.1-alpine
    environment:
      - WORKDIR=/mnt/schemas/reference
    commands:
      - /mnt/docker/validateSchema.sh
    when:
      branch:
        exclude: master
      event: push

  open-snow-change-dev:
    image: quay.io/ukhomeofficedigital/snowtify:latest
    secrets:
      - source: DEV_SERVICE_NOW_PASSWORD
        target: SNOW_TEST_PASS
      - source: DEV_SERVICE_NOW_USERNAME
        target: SNOW_TEST_USER
    environment:
      - SNOW_DESC=${DRONE_COMMIT_MESSAGE}
      - SNOW_ENDPOINT=https://cto-change-dev.internal.cto-notprod.homeoffice.gov.uk/create
      - SNOW_EXTERNAL_ID=COP
      - SNOW_INT_ID_FILE=/drone/src/internal-id
      - SNOW_TITLE=${DRONE_REPO}:${DRONE_COMMIT_SHA}
    when:
      environment: dev
      event: deployment

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    secrets:
      - source: DB_REF_DEFAULT_USERNAME
        target: DB_REF_DEFAULT_USERNAME
      - source: DB_REF_GOVERNANCE_ANON_USERNAME
        target: DB_REF_GOVERNANCE_ANON_USERNAME
      - source: DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
        target: DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
      - source: DB_REF_GOVERNANCE_OWNER_USERNAME
        target: DB_REF_GOVERNANCE_OWNER_USERNAME
      - source: DB_REF_GOVERNANCE_READONLY_USERNAME
        target: DB_REF_GOVERNANCE_READONLY_USERNAME
      - source: DB_REF_GOVERNANCE_SCHEMA
        target: DB_REF_GOVERNANCE_SCHEMA
      - source: DB_REF_GOVERNANCE_SERVICE_USERNAME
        target: DB_REF_GOVERNANCE_SERVICE_USERNAME
      - source: DB_REF_JDBC_OPTIONS
        target: DB_REF_JDBC_OPTIONS
      - source: DB_REF_OPTIONS
        target: DB_REF_OPTIONS
      - source: DB_REF_PORT
        target: DB_REF_PORT
      - source: DB_REF_PRIVATE_GITKEY
        target: DB_REF_PRIVATE_GITKEY
      - source: DB_REF_PRIVATE_GITREPO
        target: DB_REF_PRIVATE_GITREPO
      - source: PROTOCOL_POSTGRES
        target: DB_REF_PROTOCOL
      - source: DB_REF_REFERENCE_ANON_USERNAME
        target: DB_REF_REFERENCE_ANON_USERNAME
      - source: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
        target: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - source: DB_REF_REFERENCE_DBNAME
        target: DB_REF_REFERENCE_DBNAME
      - source: DB_REF_REFERENCE_OWNER_USERNAME
        target: DB_REF_REFERENCE_OWNER_USERNAME
      - source: DB_REF_REFERENCE_READONLY_USERNAME
        target: DB_REF_REFERENCE_READONLY_USERNAME
      - source: DB_REF_REFERENCE_SCHEMA
        target: DB_REF_REFERENCE_SCHEMA
      - source: DB_REF_REFERENCE_SERVICE_USERNAME
        target: DB_REF_REFERENCE_SERVICE_USERNAME
      - source: DEV_DB_REF_DEFAULT_DBNAME
        target: DB_REF_DEFAULT_DBNAME
      - source: DEV_DB_REF_DEFAULT_PASSWORD
        target: DB_REF_DEFAULT_PASSWORD
      - source: DEV_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - source: DEV_DB_REF_GOVERNANCE_OWNER_PASSWORD
        target: DB_REF_GOVERNANCE_OWNER_PASSWORD
      - source: DEV_DB_REF_HOSTNAME
        target: DB_REF_HOSTNAME
      - source: DEV_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
      - source: DEV_DB_REF_REFERENCE_OWNER_PASSWORD
        target: DB_REF_REFERENCE_OWNER_PASSWORD
      - source: GIT_REPO_PRIVATE_GITURL
        target: GIT_REPO_PRIVATE_GITURL
      - source: GIT_REPO_PRIVATE_PORT
        target: GIT_REPO_PRIVATE_PORT
      - source: GIT_REPO_PRIVATE_URL
        target: GIT_REPO_PRIVATE_URL
    commands:
      - export PRIVATE_KEY=$${DB_REF_PRIVATE_GITKEY}
      - export PRIVATE_GIT_URL="$${GIT_REPO_PRIVATE_GITURL}$${DB_REF_PRIVATE_GITREPO}.git"
      - /usr/bin/create_ssh_key.sh
      - /usr/bin/ssh-keyscan -T 10 -p $${GIT_REPO_PRIVATE_PORT} $${GIT_REPO_PRIVATE_URL}  >> ~/.ssh/known_hosts
      - git clone $${PRIVATE_GIT_URL} private-refdata
      - /mnt/docker/reset.sh
      - /mnt/docker/run.sh
      - cd /mnt/private-refdata
      - /mnt/private-refdata/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: dev

  complete-snow-change-dev:
    image: quay.io/ukhomeofficedigital/snowtify:latest
    secrets:
      - source: DEV_SERVICE_NOW_PASSWORD
        target: SNOW_TEST_PASS
      - source: DEV_SERVICE_NOW_USERNAME
        target: SNOW_TEST_USER
    environment:
      - SNOW_DESC=${DRONE_COMMIT_MESSAGE}
      - SNOW_ENDPOINT=https://cto-change-dev.internal.cto-notprod.homeoffice.gov.uk/update
      - SNOW_INT_ID_FILE=/drone/src/internal-id
      - SNOW_TITLE=${DRONE_REPO}:${DRONE_COMMIT_SHA}
    deployment_outcome: success
    when:
      environment: dev
      event: deployment
      status: success

  cancel-snow-change-dev:
    image: quay.io/ukhomeofficedigital/snowtify:latest
    secrets:
      - source: DEV_SERVICE_NOW_PASSWORD
        target: SNOW_TEST_PASS
      - source: DEV_SERVICE_NOW_USERNAME
        target: SNOW_TEST_USER
    environment:
      - SNOW_DESC=${DRONE_COMMIT_MESSAGE}
      - SNOW_ENDPOINT=https://cto-change-dev.internal.cto-notprod.homeoffice.gov.uk/update
      - SNOW_INT_ID_FILE=/drone/src/internal-id
      - SNOW_TITLE=${DRONE_REPO}:${DRONE_COMMIT_SHA}
    deployment_outcome: fail
    when:
      environment: dev
      event: deployment
      status: failure

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    secrets:
      - source: DB_REF_DEFAULT_USERNAME
        target: DB_REF_DEFAULT_USERNAME
      - source: DB_REF_GOVERNANCE_ANON_USERNAME
        target: DB_REF_GOVERNANCE_ANON_USERNAME
      - source: DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
        target: DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
      - source: DB_REF_GOVERNANCE_OWNER_USERNAME
        target: DB_REF_GOVERNANCE_OWNER_USERNAME
      - source: DB_REF_GOVERNANCE_READONLY_USERNAME
        target: DB_REF_GOVERNANCE_READONLY_USERNAME
      - source: DB_REF_GOVERNANCE_SCHEMA
        target: DB_REF_GOVERNANCE_SCHEMA
      - source: DB_REF_GOVERNANCE_SERVICE_USERNAME
        target: DB_REF_GOVERNANCE_SERVICE_USERNAME
      - source: DB_REF_JDBC_OPTIONS
        target: DB_REF_JDBC_OPTIONS
      - source: DB_REF_OPTIONS
        target: DB_REF_OPTIONS
      - source: DB_REF_PORT
        target: DB_REF_PORT
      - source: DB_REF_PRIVATE_GITKEY
        target: DB_REF_PRIVATE_GITKEY
      - source: DB_REF_PRIVATE_GITREPO
        target: DB_REF_PRIVATE_GITREPO
      - source: PROTOCOL_POSTGRES
        target: DB_REF_PROTOCOL
      - source: DB_REF_REFERENCE_ANON_USERNAME
        target: DB_REF_REFERENCE_ANON_USERNAME
      - source: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
        target: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - source: DB_REF_REFERENCE_DBNAME
        target: DB_REF_REFERENCE_DBNAME
      - source: DB_REF_REFERENCE_OWNER_USERNAME
        target: DB_REF_REFERENCE_OWNER_USERNAME
      - source: DB_REF_REFERENCE_READONLY_USERNAME
        target: DB_REF_REFERENCE_READONLY_USERNAME
      - source: DB_REF_REFERENCE_SCHEMA
        target: DB_REF_REFERENCE_SCHEMA
      - source: DB_REF_REFERENCE_SERVICE_USERNAME
        target: DB_REF_REFERENCE_SERVICE_USERNAME
      - source: STAGING_DB_REF_DEFAULT_DBNAME
        target: DB_REF_DEFAULT_DBNAME
      - source: STAGING_DB_REF_DEFAULT_PASSWORD
        target: DB_REF_DEFAULT_PASSWORD
      - source: STAGING_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - source: STAGING_DB_REF_GOVERNANCE_OWNER_PASSWORD
        target: DB_REF_GOVERNANCE_OWNER_PASSWORD
      - source: STAGING_DB_REF_HOSTNAME
        target: DB_REF_HOSTNAME
      - source: STAGING_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
      - source: STAGING_DB_REF_REFERENCE_OWNER_PASSWORD
        target: DB_REF_REFERENCE_OWNER_PASSWORD
      - source: GIT_REPO_PRIVATE_GITURL
        target: GIT_REPO_PRIVATE_GITURL
      - source: GIT_REPO_PRIVATE_PORT
        target: GIT_REPO_PRIVATE_PORT
      - source: GIT_REPO_PRIVATE_URL
        target: GIT_REPO_PRIVATE_URL
    commands:
      - export PRIVATE_KEY=$${DB_REF_PRIVATE_GITKEY}
      - export PRIVATE_GIT_URL="$${GIT_REPO_PRIVATE_GITURL}$${DB_REF_PRIVATE_GITREPO}.git"
      - /usr/bin/create_ssh_key.sh
      - /usr/bin/ssh-keyscan -T 10 -p $${GIT_REPO_PRIVATE_PORT} $${GIT_REPO_PRIVATE_URL}  >> ~/.ssh/known_hosts
      - git clone $${PRIVATE_GIT_URL} private-refdata
      - /mnt/docker/reset.sh
      - /mnt/docker/run.sh
      - cd /mnt/private-refdata
      - /mnt/private-refdata/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: staging

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    secrets:
      - source: DB_REF_DEFAULT_USERNAME
        target: DB_REF_DEFAULT_USERNAME
      - source: DB_REF_GOVERNANCE_ANON_USERNAME
        target: DB_REF_GOVERNANCE_ANON_USERNAME
      - source: DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
        target: DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
      - source: DB_REF_GOVERNANCE_OWNER_USERNAME
        target: DB_REF_GOVERNANCE_OWNER_USERNAME
      - source: DB_REF_GOVERNANCE_READONLY_USERNAME
        target: DB_REF_GOVERNANCE_READONLY_USERNAME
      - source: DB_REF_GOVERNANCE_SCHEMA
        target: DB_REF_GOVERNANCE_SCHEMA
      - source: DB_REF_GOVERNANCE_SERVICE_USERNAME
        target: DB_REF_GOVERNANCE_SERVICE_USERNAME
      - source: DB_REF_JDBC_OPTIONS
        target: DB_REF_JDBC_OPTIONS
      - source: DB_REF_OPTIONS
        target: DB_REF_OPTIONS
      - source: DB_REF_PORT
        target: DB_REF_PORT
      - source: DB_REF_PRIVATE_GITKEY
        target: DB_REF_PRIVATE_GITKEY
      - source: DB_REF_PRIVATE_GITREPO
        target: DB_REF_PRIVATE_GITREPO
      - source: PROTOCOL_POSTGRES
        target: DB_REF_PROTOCOL
      - source: DB_REF_REFERENCE_ANON_USERNAME
        target: DB_REF_REFERENCE_ANON_USERNAME
      - source: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
        target: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - source: DB_REF_REFERENCE_DBNAME
        target: DB_REF_REFERENCE_DBNAME
      - source: DB_REF_REFERENCE_OWNER_USERNAME
        target: DB_REF_REFERENCE_OWNER_USERNAME
      - source: DB_REF_REFERENCE_READONLY_USERNAME
        target: DB_REF_REFERENCE_READONLY_USERNAME
      - source: DB_REF_REFERENCE_SCHEMA
        target: DB_REF_REFERENCE_SCHEMA
      - source: DB_REF_REFERENCE_SERVICE_USERNAME
        target: DB_REF_REFERENCE_SERVICE_USERNAME
      - source: PRODUCTION_DB_REF_DEFAULT_DBNAME
        target: DB_REF_DEFAULT_DBNAME
      - source: PRODUCTION_DB_REF_DEFAULT_PASSWORD
        target: DB_REF_DEFAULT_PASSWORD
      - source: PRODUCTION_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - source: PRODUCTION_DB_REF_GOVERNANCE_OWNER_PASSWORD
        target: DB_REF_GOVERNANCE_OWNER_PASSWORD
      - source: PRODUCTION_DB_REF_HOSTNAME
        target: DB_REF_HOSTNAME
      - source: PRODUCTION_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
      - source: PRODUCTION_DB_REF_REFERENCE_OWNER_PASSWORD
        target: DB_REF_REFERENCE_OWNER_PASSWORD
      - source: GIT_REPO_PRIVATE_GITURL
        target: GIT_REPO_PRIVATE_GITURL
      - source: GIT_REPO_PRIVATE_PORT
        target: GIT_REPO_PRIVATE_PORT
      - source: GIT_REPO_PRIVATE_URL
        target: GIT_REPO_PRIVATE_URL
    commands:
      - export PRIVATE_KEY=$${DB_REF_PRIVATE_GITKEY}
      - export PRIVATE_GIT_URL="$${GIT_REPO_PRIVATE_GITURL}$${DB_REF_PRIVATE_GITREPO}.git"
      - /usr/bin/create_ssh_key.sh
      - /usr/bin/ssh-keyscan -T 10 -p $${GIT_REPO_PRIVATE_PORT} $${GIT_REPO_PRIVATE_URL}  >> ~/.ssh/known_hosts
      - git clone $${PRIVATE_GIT_URL} private-refdata
      - /mnt/docker/reset.sh
      - /mnt/docker/run.sh
      - cd /mnt/private-refdata
      - /mnt/private-refdata/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: production

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]

# services:
#   database:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#       - POSTGRES_PASSWORD=secret
