workspace:
  base: /mnt
  path: /

pipeline:
  # test:
  #   image: quay.io/ukhomeofficedigital/docker-flyway:0c81630decc5d7f6c6ec9070d7475b3f3f084153
  #   commands:
  #     - |
  #       until PGPASSWORD=secret psql -U postgres -d postgres -h database \
  #        -c "SELECT 1;" >/dev/null 2>&1; do sleep 1; done
  #     - export POSTGRES_DB="postgres"
  #     - export POSTGRES_SERVER="database"
  #     - export POSTGRES_PORT="5432"
  #     - export POSTGRES_OPTIONS=""
  #     - export FLYWAY_INIT_USER="postgres"
  #     - export FLYWAY_INIT_PASSWORD="secret"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME="refdata"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME="ownerofdataref"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD="test"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA="reference"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME="ownerofgovdata"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD="test1"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA="governance"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER="defref1"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD="test2"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER="refanonuser"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER="refserviceuser"
  #     - export FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER="refreadonlyuser"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER="govuser1"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD="test3"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER="govanonuser"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER="govserviceuser"
  #     - export FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER="govreadonlyuser"
  #     - git checkout -f master
  #     - /mnt/docker/run.sh
  #     - git reset --hard $DRONE_COMMIT
  #     - /mnt/docker/run.sh
  #   when:
  #     branch:
  #       exclude:
  #       - master
  #     event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    secrets:
      - DEV_POSTGRES_DB
      - DEV_POSTGRES_SERVER
      - DEV_POSTGRES_PORT
      - DEV_POSTGRES_OPTIONS
      - DEV_FLYWAY_INIT_USER
      - DEV_FLYWAY_INIT_PASSWORD
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER
      - DEV_FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER
      - DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER
      - PRIVATE_GIT_KEY
      - PRIVATE_GIT_PORT
      - PRIVATE_GIT_SERVER
    commands:
      - export POSTGRES_DB=$${DEV_POSTGRES_DB}
      - export POSTGRES_SERVER=$${DEV_POSTGRES_SERVER}
      - export POSTGRES_PORT=$${DEV_POSTGRES_PORT}
      - export POSTGRES_OPTIONS=$${DEV_POSTGRES_OPTIONS}
      - export FLYWAY_INIT_USER=$${DEV_FLYWAY_INIT_USER}
      - export FLYWAY_INIT_PASSWORD=$${DEV_FLYWAY_INIT_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER=$${DEV_FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER=$${DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER}
      - export PRIVATE_KEY=$${PRIVATE_GIT_KEY}
      - export PRIVATE_GIT_URL="ssh://git@$${PRIVATE_GIT_SERVER}:$${PRIVATE_GIT_PORT}/$${PRIVATE_GIT_REPO}.git private-refdata"
      - /usr/bin/create_ssh_key.sh
      - /usr/bin/ssh-keyscan -T 10 -p $${PRIVATE_GIT_PORT} $${PRIVATE_GIT_SERVER}  >> ~/.ssh/known_hosts
      - echo $${PRIVATE_GIT_URL}
      - git clone $${PRIVATE_GIT_URL}
      - /mnt/docker/reset.sh
      - /mnt/docker/run.sh
      - /mnt/private-refdata/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: dev
  
  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/docker-flyway:0c81630decc5d7f6c6ec9070d7475b3f3f084153
    secrets:
      - STAGING_POSTGRES_DB
      - STAGING_POSTGRES_SERVER
      - STAGING_POSTGRES_PORT
      - STAGING_POSTGRES_OPTIONS
      - STAGING_FLYWAY_INIT_USER
      - STAGING_FLYWAY_INIT_PASSWORD
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER
      - STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER
      - STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER
    commands:
      - export POSTGRES_DB=$${STAGING_POSTGRES_DB}
      - export POSTGRES_SERVER=$${STAGING_POSTGRES_SERVER}
      - export POSTGRES_PORT=$${STAGING_POSTGRES_PORT}
      - export POSTGRES_OPTIONS=$${STAGING_POSTGRES_OPTIONS}
      - export FLYWAY_INIT_USER=$${STAGING_FLYWAY_INIT_USER}
      - export FLYWAY_INIT_PASSWORD=$${STAGING_FLYWAY_INIT_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER=$${STAGING_FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER=$${STAGING_FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER}
      - /mnt/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: staging

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/docker-flyway:0c81630decc5d7f6c6ec9070d7475b3f3f084153
    secrets:
      - PROD_POSTGRES_DB
      - PROD_POSTGRES_SERVER
      - PROD_POSTGRES_PORT
      - PROD_POSTGRES_OPTIONS
      - PROD_FLYWAY_INIT_USER
      - PROD_FLYWAY_INIT_PASSWORD
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER
      - PROD_FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER
      - PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER
    commands:
      - export POSTGRES_DB=$${PROD_POSTGRES_DB}
      - export POSTGRES_SERVER=$${PROD_POSTGRES_SERVER}
      - export POSTGRES_PORT=$${PROD_POSTGRES_PORT}
      - export POSTGRES_OPTIONS=$${PROD_POSTGRES_OPTIONS}
      - export FLYWAY_INIT_USER=$${PROD_FLYWAY_INIT_USER}
      - export FLYWAY_INIT_PASSWORD=$${PROD_FLYWAY_INIT_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER}
      - export FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER=$${PROD_FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER}
      - export FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER=$${PROD_FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER}
      - /mnt/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: production

# services:
#   database:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#       - POSTGRES_PASSWORD=secret
