pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t refdata:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/refdata
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: [ push, deployment ]

  deploy_to_dev:
    # image: busybox
    image: quay.io/ukhomeofficedigital/refdata
    # image: quay.io/ukhomeofficedigital/refdata:$${DRONE_COMMIT_SHA}
    commands:
      - /bin/echo hello preprod
    # commands:
    #   - ./run.sh
    when:
      branch: master
      event: [ push, deployment ]
