pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t refdata:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/refdata
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: [ push, deployment ]

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/refdata:$${DRONE_COMMIT_SHA}
    secrets:
      - source: DEV_POSTGRES_DB
        target: POSTGRES_DB
      - source: DEV_POSTGRES_SERVER
        target: POSTGRES_SERVER
      - source: DEV_POSTGRES_PORT
        target: POSTGRES_PORT
      - source: DEV_FLYWAY_INIT_USER
        target: FLYWAY_INIT_USER
      - source: DEV_FLYWAY_INIT_PASSWORD
        target: FLYWAY_INIT_PASSWORD
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME
        target: FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME
        target: FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD
        target: FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA
        target: FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER
        target: FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD
        target: FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER
        target: FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER
        target: FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER
      - source: DEV_FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER
        target: FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER
      - source: DEV_FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER
        target: FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER
    when:
      branch: master
      event: [ push, deployment ]
