workspace:
  base: /mnt
  path: /

pipeline:

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    secrets:
      - DEV_DB_REF_PROTOCOL
      - DEV_DB_REF_PORT
      - DEV_DB_REF_HOSTNAME
      - DEV_DB_REF_OPTIONS
      - DEV_DB_REF_JDBC_OPTIONS
      - DEV_DB_REF_DEFAULT_USERNAME
      - DEV_DB_REF_DEFAULT_PASSWORD
      - DEV_DB_REF_DEFAULT_DBNAME
      - DEV_DB_REF_REFERENCE_DBNAME
      - DEV_DB_REF_REFERENCE_SCHEMA
      - DEV_DB_REF_REFERENCE_OWNER_USERNAME
      - DEV_DB_REF_REFERENCE_OWNER_PASSWORD
      - DEV_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - DEV_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD 
      - DEV_DB_REF_REFERENCE_ANON_USERNAME
      - DEV_DB_REF_REFERENCE_SERVICE_USERNAME
      - DEV_DB_REF_REFERENCE_READONLY_USERNAME
      - DEV_DB_REF_GOVERNANCE_SCHEMA
      - DEV_DB_REF_GOVERNANCE_OWNER_USERNAME
      - DEV_DB_REF_GOVERNANCE_OWNER_PASSWORD
      - DEV_DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
      - DEV_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - DEV_DB_REF_GOVERNANCE_ANON_USERNAME
      - DEV_DB_REF_GOVERNANCE_SERVICE_USERNAME
      - DEV_DB_REF_GOVERNANCE_READONLY_USERNAME
      - DEV_DB_REF_PRIVATE_GITREPO
      - DEV_DB_REF_PRIVATE_GITKEY
      - DEV_GIT_REPO_PRIVATE_PORT
      - DEV_GIT_REPO_PRIVATE_URL
      - DEV_GIT_REPO_PRIVATE_GITURL
    commands:
      - export DB_REF_PROTOCOL=$${DEV_DB_REF_PROTOCOL}
      - export DB_REF_PORT=$${DEV_DB_REF_PORT}
      - export DB_REF_HOSTNAME=$${DEV_DB_REF_HOSTNAME}
      - export DB_REF_OPTIONS=$${DEV_DB_REF_OPTIONS}
      - export DB_REF_JDBC_OPTIONS=$${DEV_DB_REF_JDBC_OPTIONS}
      - export DB_REF_DEFAULT_USERNAME=$${DEV_DB_REF_DEFAULT_USERNAME}
      - export DB_REF_DEFAULT_PASSWORD=$${DEV_DB_REF_DEFAULT_PASSWORD}
      - export DB_REF_DEFAULT_DBNAME=$${DEV_DB_REF_DEFAULT_DBNAME}
      - export DB_REF_REFERENCE_DBNAME=$${DEV_DB_REF_REFERENCE_DBNAME}
      - export DB_REF_REFERENCE_SCHEMA=$${DEV_DB_REF_REFERENCE_SCHEMA}
      - export DB_REF_REFERENCE_OWNER_USERNAME=$${DEV_DB_REF_REFERENCE_OWNER_USERNAME}
      - export DB_REF_REFERENCE_OWNER_PASSWORD=$${DEV_DB_REF_REFERENCE_OWNER_PASSWORD}
      - export DB_REF_REFERENCE_AUTHENTICATOR_USERNAME$${DEV_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME}
      - export DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD=$${DEV_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD}
      - export DB_REF_REFERENCE_ANON_USERNAME=$${DEV_DB_REF_REFERENCE_ANON_USERNAME}
      - export DB_REF_REFERENCE_SERVICE_USERNAME=$${DEV_DB_REF_REFERENCE_SERVICE_USERNAME}
      - export DB_REF_REFERENCE_READONLY_USERNAME=$${DEV_DB_REF_REFERENCE_READONLY_USERNAME}
      - export DB_REF_GOVERNANCE_SCHEMA=$${DEV_DB_REF_GOVERNANCE_SCHEMA}
      - export DB_REF_GOVERNANCE_OWNER_USERNAME=$${DEV_DB_REF_GOVERNANCE_OWNER_USERNAME}
      - export DB_REF_GOVERNANCE_OWNER_PASSWORD=$${DEV_DB_REF_GOVERNANCE_OWNER_PASSWORD}
      - export DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME=$${DEV_DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME}
      - export DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD=$${DEV_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD}
      - export DB_REF_GOVERNANCE_ANON_USERNAME=$${DEV_DB_REF_GOVERNANCE_ANON_USERNAME}
      - export DB_REF_GOVERNANCE_SERVICE_USERNAME=$${DEV_DB_REF_GOVERNANCE_SERVICE_USERNAME}
      - export DB_REF_GOVERNANCE_READONLY_USERNAME=$${DEV_DB_REF_GOVERNANCE_READONLY_USERNAME}
      - export DB_REF_PRIVATE_GITREPO=$${DEV_DB_REF_PRIVATE_GITREPO}
      - export DB_REF_PRIVATE_GITKEY=$${DEV_DB_REF_PRIVATE_GITKEY}
      - export GIT_REPO_PRIVATE_PORT=$${DEV_GIT_REPO_PRIVATE_PORT}
      - export GIT_REPO_PRIVATE_URL=$${DEV_GIT_REPO_PRIVATE_URL}
      - export GIT_REPO_PRIVATE_GITURL=$${DEV_GIT_REPO_PRIVATE_GITURL}
      - export PRIVATE_KEY=$${DEV_DB_REF_PRIVATE_GITKEY}
      - export PRIVATE_GIT_URL="$${DEV_GIT_REPO_PRIVATE_GITURL}/$${DEV_DB_REF_PRIVATE_GITREPO}.git private-refdata"
      - /usr/bin/create_ssh_key.sh
      - /usr/bin/ssh-keyscan -T 10 -p $${DEV_GIT_REPO_PRIVATE_PORT} $${DEV_GIT_REPO_PRIVATE_URL}  >> ~/.ssh/known_hosts
      - echo "Cloning ${PRIVATE_GIT_URL}"
      - git clone $${PRIVATE_GIT_URL}
      - /mnt/docker/reset.sh
      - /mnt/docker/run.sh
      - cd /mnt/private-refdata
      - /mnt/private-refdata/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: dev
  
  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    secrets:
      - STAGING_DB_REF_PROTOCOL
      - STAGING_DB_REF_PORT
      - STAGING_DB_REF_HOSTNAME
      - STAGING_DB_REF_OPTIONS
      - STAGING_DB_REF_JDBC_OPTIONS
      - STAGING_DB_REF_DEFAULT_USERNAME
      - STAGING_DB_REF_DEFAULT_PASSWORD
      - STAGING_DB_REF_DEFAULT_DBNAME
      - STAGING_DB_REF_REFERENCE_DBNAME
      - STAGING_DB_REF_REFERENCE_SCHEMA
      - STAGING_DB_REF_REFERENCE_OWNER_USERNAME
      - STAGING_DB_REF_REFERENCE_OWNER_PASSWORD
      - STAGING_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - STAGING_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD 
      - STAGING_DB_REF_REFERENCE_ANON_USERNAME
      - STAGING_DB_REF_REFERENCE_SERVICE_USERNAME
      - STAGING_DB_REF_REFERENCE_READONLY_USERNAME
      - STAGING_DB_REF_GOVERNANCE_SCHEMA
      - STAGING_DB_REF_GOVERNANCE_OWNER_USERNAME
      - STAGING_DB_REF_GOVERNANCE_OWNER_PASSWORD
      - STAGING_DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
      - STAGING_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - STAGING_DB_REF_GOVERNANCE_ANON_USERNAME
      - STAGING_DB_REF_GOVERNANCE_SERVICE_USERNAME
      - STAGING_DB_REF_GOVERNANCE_READONLY_USERNAME
      - STAGING_DB_REF_PRIVATE_GITREPO
      - STAGING_DB_REF_PRIVATE_GITKEY
      - STAGING_GIT_REPO_PRIVATE_PORT
      - STAGING_GIT_REPO_PRIVATE_URL
      - STAGING_GIT_REPO_PRIVATE_GITURL
    commands:
      - export DB_REF_PROTOCOL=$${STAGING_DB_REF_PROTOCOL}
      - export DB_REF_PORT=$${STAGING_DB_REF_PORT}
      - export DB_REF_HOSTNAME=$${STAGING_DB_REF_HOSTNAME}
      - export DB_REF_OPTIONS=$${STAGING_DB_REF_OPTIONS}
      - export DB_REF_JDBC_OPTIONS=$${STAGING_DB_REF_JDBC_OPTIONS}
      - export DB_REF_DEFAULT_USERNAME=$${STAGING_DB_REF_DEFAULT_USERNAME}
      - export DB_REF_DEFAULT_PASSWORD=$${STAGING_DB_REF_DEFAULT_PASSWORD}
      - export DB_REF_DEFAULT_DBNAME=$${STAGING_DB_REF_DEFAULT_DBNAME}
      - export DB_REF_REFERENCE_DBNAME=$${STAGING_DB_REF_REFERENCE_DBNAME}
      - export DB_REF_REFERENCE_SCHEMA=$${STAGING_DB_REF_REFERENCE_SCHEMA}
      - export DB_REF_REFERENCE_OWNER_USERNAME=$${STAGING_DB_REF_REFERENCE_OWNER_USERNAME}
      - export DB_REF_REFERENCE_OWNER_PASSWORD=$${STAGING_DB_REF_REFERENCE_OWNER_PASSWORD}
      - export DB_REF_REFERENCE_AUTHENTICATOR_USERNAME$${STAGING_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME}
      - export DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD=$${STAGING_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD}
      - export DB_REF_REFERENCE_ANON_USERNAME=$${STAGING_DB_REF_REFERENCE_ANON_USERNAME}
      - export DB_REF_REFERENCE_SERVICE_USERNAME=$${STAGING_DB_REF_REFERENCE_SERVICE_USERNAME}
      - export DB_REF_REFERENCE_READONLY_USERNAME=$${STAGING_DB_REF_REFERENCE_READONLY_USERNAME}
      - export DB_REF_GOVERNANCE_SCHEMA=$${STAGING_DB_REF_GOVERNANCE_SCHEMA}
      - export DB_REF_GOVERNANCE_OWNER_USERNAME=$${STAGING_DB_REF_GOVERNANCE_OWNER_USERNAME}
      - export DB_REF_GOVERNANCE_OWNER_PASSWORD=$${STAGING_DB_REF_GOVERNANCE_OWNER_PASSWORD}
      - export DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME=$${STAGING_DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME}
      - export DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD=$${STAGING_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD}
      - export DB_REF_GOVERNANCE_ANON_USERNAME=$${STAGING_DB_REF_GOVERNANCE_ANON_USERNAME}
      - export DB_REF_GOVERNANCE_SERVICE_USERNAME=$${STAGING_DB_REF_GOVERNANCE_SERVICE_USERNAME}
      - export DB_REF_GOVERNANCE_READONLY_USERNAME=$${STAGING_DB_REF_GOVERNANCE_READONLY_USERNAME}
      - export DB_REF_PRIVATE_GITREPO=$${STAGING_DB_REF_PRIVATE_GITREPO}
      - export DB_REF_PRIVATE_GITKEY=$${STAGING_DB_REF_PRIVATE_GITKEY}
      - export GIT_REPO_PRIVATE_PORT=$${STAGING_GIT_REPO_PRIVATE_PORT}
      - export GIT_REPO_PRIVATE_URL=$${STAGING_GIT_REPO_PRIVATE_URL}
      - export GIT_REPO_PRIVATE_GITURL=$${STAGING_GIT_REPO_PRIVATE_GITURL}
      - export PRIVATE_KEY=$${STAGING_DB_REF_PRIVATE_GITKEY}
      - export PRIVATE_GIT_URL="$${STAGING_GIT_REPO_PRIVATE_GITURL}/$${STAGING_DB_REF_PRIVATE_GITREPO}.git private-refdata"
      - /usr/bin/create_ssh_key.sh
      - /usr/bin/ssh-keyscan -T 10 -p $${STAGING_GIT_REPO_PRIVATE_PORT} $${STAGING_GIT_REPO_PRIVATE_URL}  >> ~/.ssh/known_hosts
      - git clone $${PRIVATE_GIT_URL}
      - /mnt/docker/reset.sh
      - /mnt/docker/run.sh
      - cd /mnt/private-refdata
      - /mnt/private-refdata/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: staging

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    secrets:
      - PRODUCTION_DB_REF_PROTOCOL
      - PRODUCTION_DB_REF_PORT
      - PRODUCTION_DB_REF_HOSTNAME
      - PRODUCTION_DB_REF_OPTIONS
      - PRODUCTION_DB_REF_JDBC_OPTIONS
      - PRODUCTION_DB_REF_DEFAULT_USERNAME
      - PRODUCTION_DB_REF_DEFAULT_PASSWORD
      - PRODUCTION_DB_REF_DEFAULT_DBNAME
      - PRODUCTION_DB_REF_REFERENCE_DBNAME
      - PRODUCTION_DB_REF_REFERENCE_SCHEMA
      - PRODUCTION_DB_REF_REFERENCE_OWNER_USERNAME
      - PRODUCTION_DB_REF_REFERENCE_OWNER_PASSWORD
      - PRODUCTION_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - PRODUCTION_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD 
      - PRODUCTION_DB_REF_REFERENCE_ANON_USERNAME
      - PRODUCTION_DB_REF_REFERENCE_SERVICE_USERNAME
      - PRODUCTION_DB_REF_REFERENCE_READONLY_USERNAME
      - PRODUCTION_DB_REF_GOVERNANCE_SCHEMA
      - PRODUCTION_DB_REF_GOVERNANCE_OWNER_USERNAME
      - PRODUCTION_DB_REF_GOVERNANCE_OWNER_PASSWORD
      - PRODUCTION_DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME
      - PRODUCTION_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD
      - PRODUCTION_DB_REF_GOVERNANCE_ANON_USERNAME
      - PRODUCTION_DB_REF_GOVERNANCE_SERVICE_USERNAME
      - PRODUCTION_DB_REF_GOVERNANCE_READONLY_USERNAME
      - PRODUCTION_DB_REF_PRIVATE_GITREPO
      - PRODUCTION_DB_REF_PRIVATE_GITKEY
      - PRODUCTION_GIT_REPO_PRIVATE_PORT
      - PRODUCTION_GIT_REPO_PRIVATE_URL
      - PRODUCTION_GIT_REPO_PRIVATE_GITURL
    commands:
      - export DB_REF_PROTOCOL=$${PRODUCTION_DB_REF_PROTOCOL}
      - export DB_REF_PORT=$${PRODUCTION_DB_REF_PORT}
      - export DB_REF_HOSTNAME=$${PRODUCTION_DB_REF_HOSTNAME}
      - export DB_REF_OPTIONS=$${PRODUCTION_DB_REF_OPTIONS}
      - export DB_REF_JDBC_OPTIONS=$${PRODUCTION_DB_REF_JDBC_OPTIONS}
      - export DB_REF_DEFAULT_USERNAME=$${PRODUCTION_DB_REF_DEFAULT_USERNAME}
      - export DB_REF_DEFAULT_PASSWORD=$${PRODUCTION_DB_REF_DEFAULT_PASSWORD}
      - export DB_REF_DEFAULT_DBNAME=$${PRODUCTION_DB_REF_DEFAULT_DBNAME}
      - export DB_REF_REFERENCE_DBNAME=$${PRODUCTION_DB_REF_REFERENCE_DBNAME}
      - export DB_REF_REFERENCE_SCHEMA=$${PRODUCTION_DB_REF_REFERENCE_SCHEMA}
      - export DB_REF_REFERENCE_OWNER_USERNAME=$${PRODUCTION_DB_REF_REFERENCE_OWNER_USERNAME}
      - export DB_REF_REFERENCE_OWNER_PASSWORD=$${PRODUCTION_DB_REF_REFERENCE_OWNER_PASSWORD}
      - export DB_REF_REFERENCE_AUTHENTICATOR_USERNAME$${PRODUCTION_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME}
      - export DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD=$${PRODUCTION_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD}
      - export DB_REF_REFERENCE_ANON_USERNAME=$${PRODUCTION_DB_REF_REFERENCE_ANON_USERNAME}
      - export DB_REF_REFERENCE_SERVICE_USERNAME=$${PRODUCTION_DB_REF_REFERENCE_SERVICE_USERNAME}
      - export DB_REF_REFERENCE_READONLY_USERNAME=$${PRODUCTION_DB_REF_REFERENCE_READONLY_USERNAME}
      - export DB_REF_GOVERNANCE_SCHEMA=$${PRODUCTION_DB_REF_GOVERNANCE_SCHEMA}
      - export DB_REF_GOVERNANCE_OWNER_USERNAME=$${PRODUCTION_DB_REF_GOVERNANCE_OWNER_USERNAME}
      - export DB_REF_GOVERNANCE_OWNER_PASSWORD=$${PRODUCTION_DB_REF_GOVERNANCE_OWNER_PASSWORD}
      - export DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME=$${PRODUCTION_DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME}
      - export DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD=$${PRODUCTION_DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD}
      - export DB_REF_GOVERNANCE_ANON_USERNAME=$${PRODUCTION_DB_REF_GOVERNANCE_ANON_USERNAME}
      - export DB_REF_GOVERNANCE_SERVICE_USERNAME=$${PRODUCTION_DB_REF_GOVERNANCE_SERVICE_USERNAME}
      - export DB_REF_GOVERNANCE_READONLY_USERNAME=$${PRODUCTION_DB_REF_GOVERNANCE_READONLY_USERNAME}
      - export DB_REF_PRIVATE_GITREPO=$${PRODUCTION_DB_REF_PRIVATE_GITREPO}
      - export DB_REF_PRIVATE_GITKEY=$${PRODUCTION_DB_REF_PRIVATE_GITKEY}
      - export GIT_REPO_PRIVATE_PORT=$${PRODUCTION_GIT_REPO_PRIVATE_PORT}
      - export GIT_REPO_PRIVATE_URL=$${PRODUCTION_GIT_REPO_PRIVATE_URL}
      - export GIT_REPO_PRIVATE_GITURL=$${PRODUCTION_GIT_REPO_PRIVATE_GITURL}
      - export PRIVATE_KEY=$${PRODUCTION_DB_REF_PRIVATE_GITKEY}
      - export PRIVATE_GIT_URL="$${PRODUCTION_GIT_REPO_PRIVATE_GITURL}/$${PRODUCTION_DB_REF_PRIVATE_GITREPO}.git private-refdata"
      - /usr/bin/create_ssh_key.sh
      - /usr/bin/ssh-keyscan -T 10 -p $${PRODUCTION_GIT_REPO_PRIVATE_PORT} $${PRODUCTION_GIT_REPO_PRIVATE_URL}  >> ~/.ssh/known_hosts
      - git clone $${PRIVATE_GIT_URL}
      - /mnt/docker/reset.sh
      - /mnt/docker/run.sh
      - cd /mnt/private-refdata
      - /mnt/private-refdata/docker/run.sh
    when:
      branch: master
      event: deployment
      environment: production

# services:
#   database:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#       - POSTGRES_PASSWORD=secret
